export const jobData = [
    {
      id: "1",
      title: "Senior Frontend Developer",
      company: "TechCorp Inc.",
      location: "San Francisco, CA",
      jobType: "Full-time",
      salary: "$120,000 - $150,000",
      matchScore: 92,
      experience: "5+ years",
      createdAt: "2 days ago",
      description:
        "We're looking for an experienced Frontend Developer to join our team. You'll be responsible for building user interfaces for our web applications using React, TypeScript, and modern CSS frameworks.",
      matchingSkills: ["React", "TypeScript", "Tailwind CSS", "Next.js", "Redux"],
      missingSkills: ["GraphQL"],
      status: "active",
    },
    {
      id: "2",
      title: "Backend Engineer",
      company: "DataSystems Ltd.",
      location: "Remote",
      jobType: "Full-time",
      salary: "$110,000 - $140,000",
      matchScore: 68,
      experience: "3-5 years",
      createdAt: "1 week ago",
      description:
        "Join our backend team to develop scalable APIs and microservices. You'll work with Node.js, Express, and MongoDB to build robust backend solutions for our enterprise clients.",
      matchingSkills: ["Node.js", "Express", "MongoDB"],
      missingSkills: ["Kubernetes", "AWS", "Docker"],
      status: "active",
    },
    {
      id: "3",
      title: "UX/UI Designer",
      company: "Creative Solutions",
      location: "New York, NY",
      jobType: "Part-time",
      salary: "$80,000 - $100,000",
      matchScore: 35,
      experience: "2+ years",
      createdAt: "3 days ago",
      description:
        "We're seeking a talented UX/UI Designer to create beautiful, intuitive interfaces for our mobile and web applications. You'll work closely with our product and development teams.",
      matchingSkills: ["Figma", "UI Design"],
      missingSkills: ["Adobe XD", "Sketch", "Prototyping", "User Research"],
      status: "active",
    },
    {
      id: "4",
      title: "Full Stack Developer",
      company: "Innovate Technologies",
      location: "Austin, TX",
      jobType: "Contract",
      salary: "$90,000 - $120,000",
      matchScore: 75,
      experience: "3+ years",
      createdAt: "Just now",
      description:
        "Looking for a versatile Full Stack Developer to help build our next-generation SaaS platform. You'll work on both frontend and backend components using modern JavaScript frameworks.",
      matchingSkills: ["JavaScript", "React", "Node.js", "SQL"],
      missingSkills: ["Vue.js", "GraphQL"],
      status: "pending",
    },
  ]
  